name: lua
on: [push, pull_request]
jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check .
          version: "0.14.0"
      - uses: jidicula/clang-format-action@v4.8.0
        with:
          clang-format-version: "14"
          check-path: lua

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: luajit-2.1.0-beta3

      - name: Symlink luajit
        run: |
          pushd .lua/bin
          ln -s lua luajit
          popd

      - name: Build extension (release)
        run: |
          pushd lua/wincent/commandt/lib
          make
          popd

      - name: Run unit tests (release)
        run: bin/test

      - name: Run stress tests (release, benchmarks)
        run: TIMES=1 bin/benchmarks/matcher.lua

      # Repeat the tests in DEBUG mode (ie. with `assert()` calls active).
      - name: Build extension (debug)
        run: |
          pushd lua/wincent/commandt/lib
          DEBUG=1 make
          popd

      - name: Run unit tests (debug)
        run: bin/test

      - name: Run stress tests (debug, benchmarks)
        run: TIMES=1 bin/benchmarks/matcher.lua
