name: lua

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  style:
    runs-on: ubuntu-22.04
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: JohnnyMorganz/stylua-action@479972f01e665acfcba96ada452c36608bdbbb5e # v4.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check .
          version: "0.20.0"
      - uses: jidicula/clang-format-action@6cd220de46c89139a0365edae93eee8eb30ca8fe # v4.16.0
        with:
          clang-format-version: "21"
          check-path: lua

  test:
    runs-on: ubuntu-22.04
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: leafo/gh-actions-lua@8c9e175e7a3d77e21f809eefbee34a19b858641b # v12.0.0
        with:
          luaVersion: luajit-openresty

      - name: Build extension (release)
        run: |
          pushd lua/wincent/commandt/lib
          make
          popd

      - name: Run unit tests (release)
        run: bin/test

      - name: Run stress tests (release, matcher benchmarks)
        run: TIMES=1 bin/benchmarks/matcher.lua

      - name: Run stress tests (release, scanner benchmarks)
        run: TIMES=1 bin/benchmarks/scanner.lua

      # Repeat the tests in DEBUG mode (ie. with `assert()` calls active).
      - name: Build extension (debug)
        run: |
          pushd lua/wincent/commandt/lib
          DEBUG=1 make
          popd

      - name: Run unit tests (debug)
        run: bin/test

      - name: Run stress tests (debug, matcher benchmarks)
        run: TIMES=1 bin/benchmarks/matcher.lua

      - name: Run stress tests (debug, scanner benchmarks)
        run: TIMES=1 bin/benchmarks/scanner.lua
